### ISSUE TITLE
Social media links are missing

### ISSUE THREAD

**Issue by bdorry** [VonageGarage/VDP#44]

**Comment by mheap** [comment]
@bdorry Which links, and where would you like them to point?

**Comment by bdorry** [comment]
Let's start with the Twitter and LinkedIn, the same links as on the Nexmo
site.

**Comment by fabianrbz** [comment]
@bdorry @mheap in order to add social media links you need to update [this file](https://github.com/VonageGarage/VDP/blob/master/config/business_info.yml)
And add the keys in the following way:
```
